package com.docprocess.config;

public class ConfigConstant {
    public static String AWS_ACCESS_KEY = "AWS_ACCESS_KEY";
    public static String AWS_SECRET_KEY = "AWS_SECRET_KEY";
    public static String DOCUMENT_STORAGE_PATH_FOR_PRINTING = "DOCUMENT_STORAGE_PATH_FOR_PRINTING";
    public static String SENDGRID_SMTP_HOST_NAME = "SENDGRID_SMTP_HOST_NAME";
    public static String SENDGRID_SMTP_PORT = "SENDGRID_SMTP_PORT";
    public static String SENDGRID_SMTP_AUTH_USER = "SENDGRID_SMTP_AUTH_USER";
    public static String SENDGRID_SMTP_AUTH_PASSWORD = "SENDGRID_SMTP_AUTH_PASSWORD";
    public static String SENDGRID_SMTP_TO_EMAIL_ADDRESS = "SENDGRID_SMTP_TO_EMAIL_ADDRESS";
    public static String SENDGRID_SMTP_FROM_EMAIL_ADDRESS = "SENDGRID_SMTP_FROM_EMAIL_ADDRESS";
    public static String RECORD_ADDED_FOR_MONITORING_CHECK = "RECORD_ADDED_FOR_MONITORING_CHECK";
    public static String AWS_S3_TEMPLATE_FOLDER_PATH = "AWS_S3_TEMPLATE_FOLDER_PATH";
    public static String DOCUMENT_TEMPLATE_PATH_ON_SERVER = "DOCUMENT_TEMPLATE_PATH_ON_SERVER";
    public static String RENDERED_FILE_PATH = "RENDERED_FILE_PATH";
    public static String ROOT_FOLDER_TO_STORE_LOCAL_FILE = "ROOT_FOLDER_TO_STORE_LOCAL_FILE";
    public static String AWS_DIGITAL_SIGN_BUCKET_NAME = "AWS_DIGITAL_SIGN_BUCKET_NAME";
    public static String AWS_DIGITAL_SIGN_BUCKET_FOLDER = "AWS_DIGITAL_SIGN_BUCKET_FOLDER";
    public static String AWS_DIGITAL_SIGN_LOCAL_FOLDER = "AWS_DIGITAL_SIGN_LOCAL_FOLDER";
//    public static String FTP_PASSWORD_FOR_PRINTING_SERVER = "FTP_PASSWORD_FOR_PRINTING_SERVER";
//    public static String AWS_S3_DOC_VALIDATION_FOLDER_PATH = "AWS_S3_DOC_VALIDATION_FOLDER_PATH";
    public static String AWS_S3_DOCUMENT_BUCKET_NAME = "AWS_S3_DOCUMENT_BUCKET_NAME";
//    public static String FTP_SERVER_PORT_FOR_PRINTING = "FTP_SERVER_PORT_FOR_PRINTING";
    public static String AWS_S3_HOME_BUCKET_NAME = "AWS_S3_HOME_BUCKET_NAME";
    public static String PDF_PASSWORD_OWNER = "PDF_PASSWORD_OWNER";

    public static String SALESFORCE_USERNAME = "SALESFORCE_USERNAME";
    public static String SALESFORCE_PASSWORD = "SALESFORCE_PASSWORD";
    public static String SALESFORCE_GRANT_TYPE = "SALESFORCE_GRANT_TYPE";
    public static String SALESFORCE_CLIENT_ID = "SALESFORCE_CLIENT_ID";
    public static String SALESFORCE_CLIENT_SECRET = "SALESFORCE_CLIENT_SECRET";
    public static String SALESFORCE_NOTIFICATION_API_ENDPOINT = "SALESFORCE_NOTIFICATION_API_ENDPOINT";
    public static String SALESFORCE_TOKEN_URL = "SALESFORCE_TOKEN_URL";

    public static String FMSAPP_USERNAME = "FMSAPP_USERNAME";
    public static String FMSAPP_PASSWORD = "FMSAPP_PASSWORD";
    public static String FMSAPP_AUTHENTICATE_API = "FMSAPP_AUTHENTICATE_API";
    public static String FMSAPP_UPDATETAG_API = "FMSAPP_UPDATETAG_API";

    public static String AWS_REGION = "AWS_REGION";
}
